### ISSUE TITLE
想问下bookstack/书栈网对此译本的搬运是得到授权的吗？

### ISSUE THREAD

**Issue by yingang** [Vonng/ddia#122]
刚无意中看到这里：https://www.bookstack.cn/books/ddia

**Comment by Vonng** [comment]
木有，不过既然保留了署名，也不算违反CC-BY 4.0 。

**Comment by yingang** [comment]
嗯嗯，没问题就行，那回头我们更新了版本，也可以考虑通知他们一下：）

**Comment by Zerozzzz** [comment]
这种分享精神值得大家尊重
