### ISSUE TITLE
序言中的本书 gitbook 链接失效了。

### ISSUE THREAD

**Issue by shukebeta** [Vonng/DDIA#135]
https://vonng.gitbooks.io/ddia-cn/content/

就是上面这个链接，如果有新链接的话，建议更新一下。

**Comment by Vonng** [comment]
It's a valid link in my browser? 
Proxy/VPN is required to access gitbook. 
Maybe try http://ddia.vonng.com/ instead in mainland China.

**Comment by shukebeta** [comment]
It seems that the original link works only when you have logged in on gitbook. You could try that link in an Incognito window. By the way, I can visit gitbook as I live in New Zealand.

**Comment by Vonng** [comment]
> It seems that the original link works only when you have logged in on gitbook. You could try that link in an Incognito window. By the way, I can visit gitbook as I live in New Zealand.

Sorry for the false assumption. :) .I will hide gitbook link to avoid confusion
Since gitbook is quite bulky, It's high recommend to use local markdown editor such as Typora or docsify in local browser.

**Comment by shukebeta** [comment]
No worries. I just noticed that gitbook has closed the legacy site. I no longer love gitbook since they moved to the "new" version. I try to find the download as epub/pdf feature but failed on gitbook. It's ok, we can still do that by using 3rd party tools.
