### ISSUE TITLE
文章每一段开头，为什么有一个空格呢？

### ISSUE THREAD

**Issue by XIJINIAN** [Vonng/DDIA#142]
阅读了 Issues，没人提出这个问题，所以询问一下是刻意这么做的吗？

（传统印刷排版，一般空两个中文文字大小的空格；网页上的排版，大家相对推崇不加任何空格。）

**Comment by yingang** [comment]
看上去显示的这个空格对应原文是一个tab字符，@Vonng 看看有没有什么特殊的考虑？

**Comment by Vonng** [comment]
原本翻译时每一段段首会有一个Tab，在Markdown编辑器中会更为美观。
不过这一格式并没有在所有的段落上强制，现在已经不统一了，我也赞同使用不缩进的方式。

**Comment by yingang** [comment]
那我批量处理一下吧，应该不麻烦。

**Comment by yingang** [comment]
已处理，请参见 f4034041fb7f3848ad86c926089308983884e98f。
