### ISSUE TITLE
第三章有很多中文翻译的不通顺

### ISSUE THREAD

**Issue by imcheney** [Vonng/DDIA#143]
http://ddia.vonng.com/#/ch3

"合并过程保持细分的数量，所以查找不需要检查许多哈希映射。 大量的细节进入实践这个简单的想法工作。"

这个看的一点都不通顺...

**Comment by yingang** [comment]
谢谢指出，我更新了一下：

每个段现在都有自己的内存散列表，将键映射到文件偏移量。为了找到一个键的值，我们首先检查最近段的哈希映射；如果键不存在，我们就检查第二个最近的段，依此类推。合并过程将保持段的数量足够小，所以查找过程不需要检查太多的哈希映射。

要让这个简单的想法在实际中能工作会涉及到大量的细节。简单来说，下面几点都是实现过程中需要认真考虑的问题：

**Comment by yingang** [comment]
如有更多翻译不当，欢迎继续指出，谢谢！

**Comment by yingang** [comment]
上周抽空把第三章重新过了一遍，大部分我能看到的不通顺应该都更新了翻译，如有处理不当或遗漏的，欢迎大家指出
