### ISSUE TITLE
间隙锁与next-key locking

### ISSUE THREAD

**Issue by secret4233** [Vonng/DDIA#144]
https://github.com/Vonng/ddia/blob/master/ch7.md#索引范围锁
此处将next-key locking翻译为间隙锁，但据我了解，Gap lock 和next-key locking 是不一样的，此处是否为误译？

**Comment by yingang** [comment]
好像next-key locking也没有常用的中文名称，要不直接用原文吧：

索引范围锁（index-range locking，也被称为next-key locking）

大家看看有没有好的想法和建议？

**Comment by secret4233** [comment]
通用的说法还是next-key locking吧，个人觉得直接用原文就好

**Comment by secret4233** [comment]
通用的说法还是next-key locking吧，个人觉得直接用原文就好

**Comment by yingang** [comment]
已更新，请参阅： 9d9bfb5ba5941d1c27bcfb2163ca82322647b79e

谢谢！
