### ISSUE TITLE
GitBook 的翻译可以整体更新下嘛？

### ISSUE THREAD

**Issue by yingang** [Vonng/DDIA#162]
@Vonng 

看上去还是比较早之前的版本了，最近半年的更新都没进去，这个方便自动更新啥的吗？

**Comment by Vonng** [comment]
Gitbook应该是自动同步的，我去看看哪里设置有问题

**Comment by Vonng** [comment]
fixed by https://github.com/Vonng/ddia/commit/3688d0ad12c6eda157a1b6e4145314c74c3bcb7e

老的连接账号忘了…，创建了一个新的Gitbook Project: [Vonng/ddia](https://vonng.gitbook.io/vonng/)

**Comment by yingang** [comment]
刚发现页面之间的跳转出问题了，GitBook似乎把目录链接都转换成了拼音：https://vonng.gitbook.io/vonng/part-ii/ch7#zhen-de-chuan-hang-zhi-hang

而页面内的链接还是原来这种：
https://vonng.gitbook.io/vonng/part-ii/ch7#%E7%9C%9F%E7%9A%84%E4%B8%B2%E8%A1%8C%E6%89%A7%E8%A1%8C

**Comment by Vonng** [comment]
这个特性有点自作聪明了，我找找有没有办法配置URL slug的地方，找了一圈木有找到。
