### ISSUE TITLE
请问能编译成epub或者mobi吗？

### ISSUE THREAD

**Issue by goace** [Vonng/DDIA#179]
请问可以吗，如果可以的话应该怎么做，或者是否有编译好的成品，可以直接放在release下？
谢谢

**Comment by yingang** [comment]
可以参考下已经close的 #116

**Comment by goace** [comment]
多谢 我参考一下

**Comment by 52fhy** [comment]
[设计数据密集型应用-中文翻译(epub,202203).zip](https://github.com/Vonng/ddia/files/8346652/-.epub.202203.zip)
