### ISSUE TITLE
Feature Request: support change to simple theme

### ISSUE THREAD

**Issue by lroolle** [Vonng/DDIA#182]
The Vue theme's *font size* and *font color Green*  reads not feeling like reading a book... I guess. Any way, it's just *personal taste issue*.

![image](https://user-images.githubusercontent.com/14071051/151484864-50da03cf-41c6-43ae-8f9b-a00e10d26e0a.png)

Compare to /The simple theme/:

![image](https://user-images.githubusercontent.com/14071051/151484829-66a62378-7e8e-4042-8744-a090f1171c24.png)

Thanks.

**Comment by yingang** [comment]
@Vonng 你看看呢？

**Comment by Vonng** [comment]
That make sense.
Closed by https://github.com/Vonng/ddia/commit/8d8272371853c60bafb4ff0f0a6c1e6560ec79d1
