### ISSUE TITLE
小标题无法跳转

### ISSUE THREAD

**Issue by leo-987** [Vonng/DDIA#185]
http://ddia.vonng.com/
![image](https://user-images.githubusercontent.com/8790163/154784261-28f108c2-1307-4c19-aa98-7ebc31fc768f.png)
点击左侧目录的某个章节，地址栏有变化，但是浏览器无法跳转。

**Comment by yingang** [comment]
@Vonng 我尝试 undo 了你为 #182 做的修改，看上去侧边栏的小标题跳转就没有问题了，但不清楚具体的原因。麻烦看一下应该如何处理更好？

**Comment by Vonng** [comment]
呃，那个没有配置定期同步，我手工更新了一下，now it works, thanks~~
