### ISSUE TITLE
第四章的 typo 更正后，网页阅读版未更新

### ISSUE THREAD

**Issue by BeBraveBeCurious** [Vonng/DDIA#188]
盖面 --> 改变；请问是什么原因呢？谢谢

![image](https://user-images.githubusercontent.com/42266336/157998335-4fae0805-d263-4da6-b0b1-113e83ffefa1.png)
![image](https://user-images.githubusercontent.com/42266336/157998367-fede3fab-3ae1-4626-a9a9-ed478fc2ab6e.png)

**Comment by yingang** [comment]
你好，gitbooks的访问地址更新过了，原来的那个没法和最新的翻译更新同步：

https://vonng.gitbook.io/vonng/part-i/ch4#jsonxml-he-er-jin-zhi-bian-ti
