### ISSUE TITLE
第一章中的部分图片挂掉了

### ISSUE THREAD

**Issue by rovernerd** [Vonng/DDIA#189]
![image](https://user-images.githubusercontent.com/35713119/158001031-1b4db1b1-af12-47d6-907e-214cc9351633.png)

**Comment by yingang** [comment]
应该是网络访问的问题吧？我看了下github本身、gitbook、github pages都可以正常查看图片。

**Comment by yingang** [comment]
我将关闭此issue，如有进一步的问题请随时沟通。
