### ISSUE TITLE
REST 是否是一个协议呢？

### ISSUE THREAD

**Issue by BeBraveBeCurious** [Vonng/DDIA#195]
REST is not a protocol, but rather a design philosophy that builds upon the principles of HTTP [34, 35]. REST 不是一个协议，[RedHat ](https://www.redhat.com/zh/topics/integration/whats-the-difference-between-soap-rest)

在 Current directions for RPC 章节前一段：
All of these factors mean that there’s no point trying to make a remote service look too much like a local object in your programming language, because it’s a fundamentally different thing. Part of the appeal of REST is that **it doesn’t try to hide the fact that it’s a network protocol** (although this doesn’t seem to stop people from building RPC libraries on top of REST).

这一段 的 doesn't 是不是 否定前置呢？
REST 试图隐藏它不是一个网络协议

**Comment by yingang** [comment]
否定前置也只是把not改到hide前面（试图不隐藏它是网络协议的事实）而不是it's后面（试图隐藏它不是一个网络协议的事实）？后者也不会用appeal来描述吧。

不过，和前面那句在字面上确实有点不太对付。我是理解成REST不是一个具体的网络协议，但仍然是一个主要适用于网络场景下的设计方式？

**Comment by yingang** [comment]
如果暂时没有进一步的修改意见，我就先关闭这个 issue 了哈。
