### ISSUE TITLE
很多图都挂了，作者能再配一下吗

### ISSUE THREAD

**Issue by Style980102** [Vonng/DDIA#219]

**Comment by yingang** [comment]
应该是GitHub的访问不畅问题吧？通过下面这些方式来查看呢：

> 使用 [Typora](https://www.typora.io/)、[Gitbook](https://vonng.gitbook.io/vonng/) 或 [Github Pages](https://vonng.github.io/ddia) 以获取最佳阅读体验。

**Comment by yingang** [comment]
如果没有进一步的问题，我先关闭此 issue 了哈。
