### ISSUE TITLE
在线预览网站打不开

### ISSUE THREAD

**Issue by bluebear4** [Vonng/DDIA#238]
http://ddia.vonng.com/#/ 打不开 一直显示加载中 是我的问题还是链接已失效

**Comment by yingang** [comment]
我今天也是一样打不开，网站自身访问的问题吧，建议晚点再试试，应该不会是永久性的。

可以先看gitbook的版本：https://vonng.gitbook.io/vonng/

**Comment by Vonng** [comment]
cdn.jsdelivr.net is blocked.
Now using local js/css file instead, fixed by https://github.com/Vonng/ddia/commit/9a94881e37d92c2c76ba6e3f9dbf909a0bfce39d
