### ISSUE TITLE
网站404 not found

### ISSUE THREAD

**Issue by 2w1nd** [Vonng/DDIA#254]
![image](https://user-images.githubusercontent.com/64266855/181919997-e5b2bfd1-0566-413c-8adf-1019f4f892ad.png)

**Comment by yingang** [comment]
网络问题？我刚看了下 gitbook, github pages 都可以正常访问

**Comment by 2w1nd** [comment]
> 网络问题？我刚看了下 gitbook, github pages 都可以正常访问

好像是这个域名不行了http://ddia.vonng.com/#/，用这个https://vonng.github.io/ddia/#/可以访问了

**Comment by yingang** [comment]
好的，前一个域名的内容也很久没更新了，首页上放的是后一个域名，内容实时更新。
