### ISSUE TITLE
关于无主复制的疑问

### ISSUE THREAD

**Issue by SpikeWong** [Vonng/DDIA#259]
>在数据库中使用 LWW 的唯一安全方法是确保一个键只写入一次，然后视为不可变，从而避免对同一个键进行并发更新。例如，Cassandra 推荐使用的方法是使用 UUID 作为键，从而为每个写操作提供一个唯一的键

不太明白这句话是什么意思？我理解写入的对象是一个 row 或者 document，对同一个 row 和 document 的多个写操作通过 uuid 这种唯一键进行区别的意义在于？能够解决什么问题呢？

**Comment by yingang** [comment]
我理解是对 row 或 document 更新时，不直接更新当前的记录，而是创建一条新的记录，最终通过时间戳等来区分先后，避免并发更新同一条记录可能带来的不安全。

**Comment by haifeiWu** [comment]
这是原文，
The only safe way of using a database with LWW is to ensure that a key is only written once and thereafter treated as immutable, thus avoiding any concurrent updates to the same key. For example, a recommended way of using Cassandra is to use a UUID as the key, thus giving each write operation a unique key.

原文中对最后一句话还有一个引用，文章的标题是：
Jonathan Ellis: “Why Cassandra Doesn’t Need Vector Clocks,” datastax.com, September 2, 2013.

**Comment by yingang** [comment]
没有进一步的疑问我就先关闭这个 Issue 了哈。
