### ISSUE TITLE
十二张思维导图分析

### ISSUE THREAD

**Issue by ccxhwmy** [Vonng/DDIA#261]
你好~
我注意到每个章节都有一张思维导图，但是我不清楚对这些思维导图的理解是否正确，并且也没有找到对这些思维导图的解释，能否提供一些线索？
感谢！

**Comment by yingang** [comment]
你好，是指每章开头那张地图？我理解应该没有太特别的含义，主要的内容也被正文覆盖到了，地图上的位置布局基本提现了主要概念之间的联系，算是增加一些趣味性吧：）

**Comment by ccxhwmy** [comment]
> 你好，是指每章开头那张地图？我理解应该没有太特别的含义，主要的内容也被正文覆盖到了，地图上的位置布局基本提现了主要概念之间的联系，算是增加一些趣味性吧：）

明白了，谢谢！
