### ISSUE TITLE
GitBook WeChat Group QRcode Expired

### ISSUE THREAD

**Issue by auula** [Vonng/DDIA#269]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/38412458/193504213-f1c8f476-0448-4024-801f-0c6810dbc572.png">

您好！在线阅读地址二维码过期，希望你能帮忙拉我一下进群，或者说你可以回复你的微信号，我添加你，帮忙拉我进去读者交流群谢谢！

**Comment by yingang** [comment]
话说，这个是在哪里看到的？

**Comment by auula** [comment]
> 话说，这个是在哪里看到的？

一个在线阅读地址，看到的，我忘记在哪里了，如果有相关的微信群的话可以拉我一下，谢谢，没有就算了。

**Comment by yingang** [comment]
> 

ok，我也不清楚是否有类似的微信群，如果能找到具体的在线阅读地址可以再确认下。
