### ISSUE TITLE
第9章 什么使得系统线性一致，列举CAS情况出现两个x=V old

### ISSUE THREAD

**Issue by codexvn** [Vonng/DDIA#279]
http://ddia.vonng.com/#/ch9?id=%E4%B8%80%E8%87%B4%E6%80%A7%E4%BF%9D%E8%AF%81:~:text=%E3%80%82-,%E5%A6%82%E6%9E%9C,-x%E2%89%A0v_%7Bold

出现两个x=V old

**Comment by yingang** [comment]
好像是 Github Pages 上渲染的问题？直接在 Github 上查看似乎是正常的：

![image](https://user-images.githubusercontent.com/1246410/209492492-5f09dfa5-a17c-4660-a1b8-6d4cafc364c8.png)

VSCode 本地的渲染也是对的。

**Comment by codexvn** [comment]
似乎是的，是否考虑换成中文的不等于？

**Comment by codexvn** [comment]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/24852067/209979225-36f2f22b-80d7-4b4a-980d-78f8aa16a4e4.png">
<img width="164" alt="image" src="https://user-images.githubusercontent.com/24852067/209979274-e732a1eb-72bc-48cc-86b1-f754d0c3995e.png">
分别是mac上的Chrome和火狐，显示都不正常

**Comment by yingang** [comment]
@Vonng 抽空看下有什么建议不？

**Comment by yingang** [comment]
刚才试着把不等于用 `\neq` 来表示，好像也不行（不确定是不是 GitHub pages 没有及时更新），就直接更新成中文了，先这样吧。
