### ISSUE TITLE
日期被错误解析为 emoji

### ISSUE THREAD

**Issue by 117503445** [Vonng/DDIA#292]
## 问题描述

在 <https://vonng.github.io/ddia/#/ch10> 中的

`日志的这一行表明在 2015 年 2 月 27 日 17:55:11 UTC`

其中 `:55:` 被解析为了 `<img class="emoji" src="https://github.githubassets.com/images/icons/emoji/55.png" alt="55">`

## 解决方法

可以把 17:55:11 变为 \`17:55:11\`

也可以禁用 emoji 解析 `window.$docsify = { noEmoji: true };`，参考 <https://github.com/docsifyjs/docsify/issues/853>

**Comment by yingang** [comment]
采用了更新译文的方法，谢谢发现问题！
