### ISSUE TITLE
生成epub无法正确显示公式

### ISSUE THREAD

**Issue by zzzchuu** [Vonng/DDIA#303]
用gitbook生成的epub无法渲染latex内连公式，
并且我看了之前几个issue大家提交的epub文件，都有同样的问题。

如图：
![screenshot 2023-04-01 23 55 16](https://user-images.githubusercontent.com/40953911/229301130-3022a156-612e-4ca0-a43a-4aa7aa2bf45e.png)

**Comment by rabomen** [comment]
似乎gitbook是有mathjax这样的插件，但已不再维护，我安装不了。如果有人找到解决的方法欢迎讨论。
