### ISSUE TITLE
为什么英文原版丢失了很多章节

### ISSUE THREAD

**Issue by starsea** [Vonng/DDIA#324]
以 http://ddia.vonng.com/#/en-us/ch5 这里为例

**Comment by yingang** [comment]
英文应该是有意没放原文，只放了各个章节的概要和总结。

**Comment by starsea** [comment]
> 英文应该是有意没放原文，只放了各个章节的概要和总结。

请问下哪里有英文版的 html 版本呢 网上搜了一圈只有 PDF 的

**Comment by yingang** [comment]
我也不清楚了，这边跟踪的主要还是中文翻译版本哈，我先关闭这个 issue 了。
