### ISSUE TITLE
第六章似乎存在一处翻译错误

### ISSUE THREAD

**Issue by Lyianu** [Vonng/DDIA#329]
Chapter 6: Partitioning - Rebalancing Partitions - Dynamic partitioning一节中第一段
> if you got the boundaries wrong, you could end up with all of the data in one
partition and all of the other partitions empty.

原翻译为：

>如果出现边界错误，则可能会导致一个分区中的所有数据或者其他分区中的所有数据为空。

是否应该翻译为

>如果边界设置错误，可能会导致所有数据都在一个分区中，而其他分区则为空。

**Comment by yingang** [comment]
确实是翻译错了，已修正： 3fc10b900ef83f017eab6173d52a1d8dacab85db

感谢！
