### ISSUE TITLE
目录好像有点问题

### ISSUE THREAD

**Issue by msxfXF** [Vonng/DDIA#336]
比如点到第二章，第二章大标题的目录，反倒出现在小标题下方
<img width="1308" alt="image" src="https://github.com/Vonng/ddia/assets/38368353/f6041b22-fd84-4643-ac1c-4ad725b08d1e">

**Comment by yingang** [comment]
@Vonng 问下你这边清楚这个是什么问题吗？看上去确实有点奇怪

**Comment by Vonng** [comment]
这个是 http://ddia.vonng.com/#/ch2 这里的吗？我看一下吧。
https://vonng.github.io/ddia/#/ch2 可能用 github pages 会更合适因为会实时更新。

**Comment by yingang** [comment]
> 这个是 http://ddia.vonng.com/#/ch2 这里的吗？我看一下吧。 https://vonng.github.io/ddia/#/ch2 可能用 github pages 会更合适因为会实时更新。

我这边看 https://vonng.github.io/ddia/#/part-ii 也是一样的，查看几个 part-xx 页面时，其目录都会显示在该 part 所包含的章节目录的后面
