### ISSUE TITLE
关于图9-4的解释

### ISSUE THREAD

**Issue by tigerinus** [Vonng/DDIA#339]
> 客户 B 的最后一次读取（阴影条柱中）不是线性一致性的。该操作与 C 的 cas 写操作并发（它将 x 从 2 更新为 4 ）。在没有其他请求的情况下，B 的读取返回 2 是可以的。

这句话不能完全理解：
1. 既然“不是线性一致性的”，为什么后面又说“B 的读取返回 2 是可以的”？
2. 什么叫“在没有其他请求的情况下”？“其他请求”指的是什么？

**Comment by yingang** [comment]
按我的理解合并回答一下哈：

1. 这里的其他请求是指图里Client A的第二次读取操作，该操作读取到了Client C的写入操作的结果（即将x从2改为4）
2. 如果没有这个其他请求，Client B的最后一次读取操作和Client C的写入操作是并发的，读取到2或4都有可能，所以原文会说读取到2也是可以的
3. 但因为已经有了这个其他请求，不管Client B和Client C的操作怎么并发，至少Client A已经看到了Client C的写入结果，那发生时间更晚的Client B读取操作也必须能看到这个结果，这样才能说满足线性一致性的要求

**Comment by tigerinus** [comment]
> 按我的理解合并回答一下哈：
> 
> 1. 这里的其他请求是指图里Client A的第二次读取操作，该操作读取到了Client C的写入操作的结果（即将x从2改为4）
> 2. 如果没有这个其他请求，Client B的最后一次读取操作和Client C的写入操作是并发的，读取到2或4都有可能，所以原文会说读取到2也是可以的
> 3. 但因为已经有了这个其他请求，不管Client B和Client C的操作怎么并发，至少Client A已经看到了Client C的写入结果，那发生时间更晚的Client B读取操作也必须能看到这个结果，这样才能说满足线性一致性的要求

所以这个图只是说明了一种不符合线性一致性的反例，并不是说明如何保证线性一致性的机制，对么？

**Comment by yingang** [comment]
> 所以这个图只是说明了一种不符合线性一致性的反例，并不是说明如何保证线性一致性的机制，对么？

嗯，我理解是的，具体如何设计和实现应该是后面的章节所讨论的内容。

**Comment by yingang** [comment]
没有进一步的疑问，就先 close 这个 issue 了哈。
