### ISSUE TITLE
第二版第一章有一处翻译不太妥当

### ISSUE THREAD

**Issue by Vermouth1995** [Vonng/DDIA#346]
[术语：前端与后端](https://ddia2.pigsty.io/#/ch1?id=%e6%9c%af%e8%af%ad%ef%bc%9a%e5%89%8d%e7%ab%af%e4%b8%8e%e5%90%8e%e7%ab%af)

原文：

> it usually consists of some application code that reads and writes data in one or more databases, and sometimes interfaces with additional data systems such as caches or message queues (which we might collectively call data infrastructure).

原翻译为：

> 它通常包含一些应用程序代码，这些代码在一个或多个数据库中读写数据，有时还会与额外的数据系统（如缓存或消息队列）**_接口_**（我们可能统称为数据基础设施）。

是否应该翻译为：

> 它通常包含一些应用程序代码，这些代码在一个或多个数据库中读写数据，有时还会与额外的数据系统（如缓存或消息队列）**_交互_**（我们可能统称为数据基础设施）。

**Comment by hli988** [comment]
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/0632aaa9-9012-4c5f-87c0-3933bb9d3cd4">
是的。

Interfaces在这里是把Interface当动词使用，当`interface`是动词的话，表示interact with。应该翻译成**交互**。
原翻译应该是把`interface`当作名词**接口**来翻译了。

**Comment by yingang** [comment]
PR 已合并，感谢~
