### ISSUE TITLE
第十一章 传递事件流 部分有重复内容

### ISSUE THREAD

**Issue by b7woreo** [Vonng/ddia#40]
重复内容：  
> 当输入是一个文件（一个字节序列），第一个处理步骤通常是将其解析为一系列记录。在流处理的上下文中，记录通常被叫做事件（event），但它本质上是一样的：一个小的，自包含的，不可变的对象，包含某个时间点发生的某件事情的细节。一个事件通常包含一个来自时钟的时间戳，以指明事件发生的时间（参见“单调钟与时钟”）。
> ​ 例如，发生的事件可能是用户采取的行动，例如查看页面或进行购买。它也可能来源于机器，例如对温度传感器或CPU利用率的周期性测量。在“使用Unix工具进行批处理”的示例中，Web服务器日志的每一行都是一个事件。
> ​ 事件可能被编码为文本字符串或JSON，或者某种二进制编码，如第4章所述。这种编码允许你存储一个事件，例如将其附加到一个文件，将其插入关系表，或将其写入文档数据库。它还允许你通过网络将事件发送到另一个节点以进行处理。

**Comment by Vonng** [comment]
tks, 已修复～
