### ISSUE TITLE
生成pdf

### ISSUE THREAD

**Issue by amber-moe** [Vonng/ddia#56]
请问怎么把所有的md文档生成一个像电子书一样的pdf

**Comment by Vonng** [comment]
对应gitbook页面应该有自动生成的下载

冯若航（Ruohang Feng）

在 2019年11月28日，15:48，Amber Zhang <notifications@github.com> 写道：

﻿

请问怎么把所有的md文档生成一个像电子书一样的pdf

**Comment by wizardforcel** [comment]
```
npm install -g gitbook-cli
gitbook fetch 3.2.3
gitbook pdf
```
