### ISSUE TITLE
ch4.md 一处翻译错误

### ISSUE THREAD

**Issue by q00218426** [Vonng/ddia#90]
> 在部署应用程序的新版本（至少是服务器端应用程序）时，您可能会在几分钟内完全用新版本替换旧版本。**数据库内容也是如此**：五年前的数据仍然存在于原始编码中，除非您已经明确地重写了它。这种观察有时被总结为数据超出代码。

原文：
> When you deploy a new version of your application (of a server-side application, at least), you may entirely replace the old version with the new version within a few minutes. **The same is not true of database contents**: the five-year-old data will still be there, in the original encoding, unless you have explicitly rewritten it since then. This observation is sometimes summed up as data outlives code.

**Comment by jasonlei-chn** [comment]
数据库内容却不是如此
